### ISSUE TITLE
exporter doesn't send the username to the devices

### ISSUE THREAD

**Issue by StefanescuCristian** [oGi4i/mikrotik-exporter#10]
Hi,

I don't know if it's my setup or not, I've recreated the docker container and removed and added the user again on mikrotik and I'm lost.

It seems that the exporter doesn't send the username (or at least that is what I see in the MK device logs) and the exporter cannot login:

![image](https://user-images.githubusercontent.com/1718660/161633174-ecf3704b-0426-4f92-ae03-ef12e72b4879.png)

ROS 7.1.5, tried on arm and mipsbe, tried with and without user-manager package installed.

My config.yml is something like this:

```
devices:
  - name: MK-Berceni
    address: <redacted>
    user: prometheus
    password: <redacted>
  - name: MK-SW-Berceni
    address: <redacted>
    user: prometheus
    password: <redacted>
  - name: MK-GW-Bragadiru
    address: <redacted>
    user: prometheus
    password: <redacted>

features:
  bgp: false
  dhcp: true
  dhcpv6: true
  dhcpl: true
  dhcp_leases: true
  routes: true
  pools: true
  optics: true
  wlansta: true
  wlanif: true
  ipsec: true
  ipsec-peers: true
  monitor: true
  health: true
  conntrack: true
  pool: true
  resource: true
```

```
docker run --rm  -p 9543:9436 -v $PWD:/config ogi4i/mikrotik-exporter -config-file /config/mkt-config.yml
{"device":"MK-Berceni","error":"failed to create client: from RouterOS device: invalid user name or password (6)","level":"error","msg":"failed to collect metrics","time":"2022-04-04T21:10:21Z"}
{"device":"MK-GW-Bragadiru","error":"failed to create client: from RouterOS device: invalid user name or password (6)","level":"error","msg":"failed to collect metrics","time":"2022-04-04T21:10:21Z"}
{"device":"MK-SW-Berceni","error":"failed to create client: from RouterOS device: invalid user name or password (6)","level":"error","msg":"failed to collect metrics","time":"2022-04-04T21:10:21Z"}
```

Any ideas?
